import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          {/* <div className="flex min-h-screen"> */}
          {/* Sidebar */}
          {/* <Sidebar /> */}

          {/* Main Content */}
          {/* <div className="flex-1 ml-64  p-6 bg-gray-100"> */}
          {children}
          {/* </div> */}
          {/* </div> */}

      </body>
    </html>
  );
}
